setwd("C:/Users/vical/Desktop/Analisis_diversidad_funcional")
library(ade4)
library(mFD)
library(vegan)
library(gawdis)
library(ggplot2)
library(readxl)
Traits_Invert <- read.csv("Rasgos_invert_final_1.csv", header = T, sep = ",")
row.names(Traits_Invert) <- Traits_Invert[,1]
Traits_invert1 <- Traits_Invert[,-1]
View(Traits_invert1)
Traits_invert2$Movilidad <- as.ordered(Traits_invert2$Movilidad)
Traits_invert1$Movilidad <- as.ordered(Traits_invert2$Movilidad)
Traits_invert1$Posicion_espacial <- as.ordered(Traits_invert2$Posicion_espacial)
Traits_invert1$Movilidad <- as.ordered(Traits_invert1$Movilidad)
Traits_invert1$Posicion_espacial <- as.ordered(Traits_invert1$Posicion_espacial)
Traits_invert1$Dieta <- as.factor(Traits_invert1$Dieta)
Traits_invert1$Comportamiento <- as.factor(Traits_invert1$Comportamiento)
Traits_type1 <- read.csv("Traits_type_1.csv", sep = ",", header = T)
Entidadesfuncionales <- sp.to.fe(Traits_invert1, Traits_type1, fe_nm_type = "fe_rank")
Entidadesfuncionales
df_entifuncionales <- data.frame(Entidadesfuncionales$sp_fe)
df_entifuncionales
abund_invert <- read.csv("abund_invert1.csv", header = T, sep = ",")
row.names(abund_invert) <- abund_invert[,1]
abund_invert1 <- abund_invert [,-1]
abund_invert <- data.matrix(abund_invert1)
Indicesfuncionales_ef <- alpha.fd.fe(abund_invert, Entidadesfuncionales, details_returned = TRUE)
asb_sp_invert_summ <- mFD::asb.sp.summary(asb_sp_w = abund_invert)
asb_sp_invert_occ <- asb_sp_invert_summ$'asb_sp_occ'
alpha.fd.fe_invert <- alpha.fd.fe(asb_sp_occ = asb_sp_invert_occ, sp_to_fe = Entidadesfuncionales, ind_nm = c('fred', 'fored', 'fvuln'), check_input = TRUE, details_returned = TRUE)
alpha.fd.fe_invert$asb_fdfe
sp_dist_invert <- mFD::funct.dist(sp_tr = Traits_invert1, tr_cat = Traits_type1, metric = "gower", scale_euclid = "scale_center", ordinal_var = "classic", weight_type = "equal", stop_if_NA = TRUE)
fspaces_quality_invert <- mFD::quality.fspaces(sp_dist = sp_dist_invert, maxdim_pcoa = 10, deviation_weighting = 'absolute', fdist_scaling = FALSE, fdendro = 'average')
sp_faxes_coord_invert <- fspaces_quality_invert$details_fspaces$sp_pc_coord
alpha_fd_indices_invert <- mFD::alpha.fd.multidim(sp_faxes_coord = sp_faxes_coord_invert[, c('PC1', 'PC2', 'PC3', 'PC4')], asb_sp_w = abund_invert, ind_vect = c('fric'), scaling = TRUE, check_input = TRUE, details_returned = TRUE)
fd_ind_values_invert <- alpha_fd_indices_invert$functional_diversity_indices
fd_ind_values_invert
plot_pianguita_d <- mFD::alpha.fd.fe.plot(alpha_fd_fe = alpha.fd.fe_invert, plot_asb_nm = c("Pianguita_d"), plot_ind_nm = c("fred", "fored", "fvuln"), name_file = NULL, color_fill_fored = "darkolivegreen2", color_line_fred = "darkolivegreen4", color_fill_bar = "grey80", color_fill_fvuln = "lightcoral", color_arrow_fvuln = "indianred4", size_line_fred = 1.5, size_arrow_fvuln = 1, check_input = TRUE)
plot_pianguita_d
plots_alpha_pianguita <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Pianguita_d", "Pianguita_w"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 1, asb2 = 1), color_sp = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#DCE319FF"), color_vert = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#DCE319FF"), fill_sp = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"), fill_vert = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"), color_ch = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"), fill_ch = c(pool = "white", asb1 = "#1F968BFF", asb2 = "#DCE319FF"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_pianguita
plots_alpha_pianguita_d <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Pianguita_d"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 1, asb2 = 1), color_sp = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#DCE319FF"), color_vert = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#DCE319FF"), fill_sp = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"), fill_vert = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"), color_ch = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"), fill_ch = c(pool = "white", asb1 = "#1F968BFF", asb2 = "#DCE319FF"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_pianguita_d$fric$PC1_PC2
plots_alpha_pianguita_w <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Pianguita_w"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 1, asb2 = 1), color_sp = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#DCE319FF"), color_vert = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#DCE319FF"), fill_sp = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"), fill_vert = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"), color_ch = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"), fill_ch = c(pool = "white", asb1 = "#1F968BFF", asb2 = "#DCE319FF"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_pianguita_w$fric$PC1_PC2
plots_alpha_pianguita$fric$PC1_PC2
plots_alpha_pianguita_w$fric$patchwork
plots_alpha_pianguita$fric$patchwork
plots_alpha_pianguita_w <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Pianguita_w"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21), size_sp = c(pool = 0.7, asb1 = 1), color_sp = c(pool = "grey50", asb1 = "#1F968BFF"), color_vert = c(pool = "grey50", asb1 = "#1F968BFF"), fill_sp = c(pool = NA, asb1 = "#1F968BFF"), fill_vert = c(pool = NA, asb1 = "#1F968BFF"), color_ch = c(pool = NA, asb1 = "#1F968BFF"), fill_ch = c(pool = "white", asb1 = "#1F968BFF"), alpha_ch = c(pool = 1, asb1 = 0.3), shape_centroid_fdis = c(asb1 = 22), shape_centroid_fdiv = c(asb1 = 22), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_pianguita_w$fric$PC1_PC2
plots_alpha_pianguita_w <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Pianguita_w"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21), size_sp = c(pool = 0.7, asb1 = 2), color_sp = c(pool = "grey50", asb1 = "#1F968BFF"), color_vert = c(pool = "grey50", asb1 = "#1F968BFF"), fill_sp = c(pool = NA, asb1 = "#1F968BFF"), fill_vert = c(pool = NA, asb1 = "#1F968BFF"), color_ch = c(pool = NA, asb1 = "#1F968BFF"), fill_ch = c(pool = "white", asb1 = "#1F968BFF"), alpha_ch = c(pool = 1, asb1 = 0.3), shape_centroid_fdis = c(asb1 = 22), shape_centroid_fdiv = c(asb1 = 22), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_pianguita_w$fric$PC1_PC2
plots_alpha_pianguita_w <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Pianguita_w"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21), size_sp = c(pool = 0.7, asb1 = 4), color_sp = c(pool = "grey50", asb1 = "#1F968BFF"), color_vert = c(pool = "grey50", asb1 = "#1F968BFF"), fill_sp = c(pool = NA, asb1 = "#1F968BFF"), fill_vert = c(pool = NA, asb1 = "#1F968BFF"), color_ch = c(pool = NA, asb1 = "#1F968BFF"), fill_ch = c(pool = "white", asb1 = "#1F968BFF"), alpha_ch = c(pool = 1, asb1 = 0.3), shape_centroid_fdis = c(asb1 = 22), shape_centroid_fdiv = c(asb1 = 22), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_pianguita_w$fric$PC1_PC2
plots_alpha_pianguita_d <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Pianguita_d"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21), size_sp = c(pool = 0.7, asb1 = 4), color_sp = c(pool = "grey50", asb1 = "#1F968BFF"), color_vert = c(pool = "grey50", asb1 = "#1F968BFF"), fill_sp = c(pool = NA, asb1 = "#1F968BFF"), fill_vert = c(pool = NA, asb1 = "#1F968BFF"), color_ch = c(pool = NA, asb1 = "#1F968BFF"), fill_ch = c(pool = "white", asb1 = "#1F968BFF"), alpha_ch = c(pool = 1, asb1 = 0.3), shape_centroid_fdis = c(asb1 = 22), shape_centroid_fdiv = c(asb1 = 22), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_pianguita_d$fric$PC1_PC2
plots_alpha_pianguita_w <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Pianguita_w"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#1F968BFF"), color_vert = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#1F968BFF"), fill_sp = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#1F968BFF"), fill_vert = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#1F968BFF"), color_ch = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#1F968BFF"), fill_ch = c(pool = "white", asb1 = "#1F968BFF", asb2 = "#1F968BFF"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_pianguita_w
plots_alpha_pianguita_d <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Pianguita_d"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#1F968BFF"), color_vert = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#1F968BFF"), fill_sp = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#1F968BFF"), fill_vert = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#1F968BFF"), color_ch = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#1F968BFF"), fill_ch = c(pool = "white", asb1 = "#1F968BFF", asb2 = "#1F968BFF"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_pianguita_d$fric$PC1_PC2
plots_alpha_Punta_Soldado_w <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Punta_Soldado_w"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#440154FF", asb2 = "#440154FF"), color_vert = c(pool = "grey50", asb1 = "#440154FF", asb2 = "#440154FF"), fill_sp = c(pool = NA, asb1 = "#440154FF", asb2 = "#440154FF"), fill_vert = c(pool = NA, asb1 = "#440154FF", asb2 = "#440154FF"), color_ch = c(pool = NA, asb1 = "#440154FF", asb2 = "#440154FF"), fill_ch = c(pool = "white", asb1 = "#440154FF", asb2 = "#440154FF"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_Punta_Soldado_w$fric$PC1_PC2
plots_alpha_Punta_Soldado_d <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Punta_Soldado_d"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#440154FF", asb2 = "#440154FF"), color_vert = c(pool = "grey50", asb1 = "#440154FF", asb2 = "#440154FF"), fill_sp = c(pool = NA, asb1 = "#440154FF", asb2 = "#440154FF"), fill_vert = c(pool = NA, asb1 = "#440154FF", asb2 = "#440154FF"), color_ch = c(pool = NA, asb1 = "#440154FF", asb2 = "#440154FF"), fill_ch = c(pool = "white", asb1 = "#440154FF", asb2 = "#440154FF"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_Punta_Soldado_d$fric$PC1_PC2
plots_alpha_San_Pedro_w <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("San_Pedro_w"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#95D840FF", asb2 = "#95D840FF"), color_vert = c(pool = "grey50", asb1 = "#95D840FF", asb2 = "#95D840FF"), fill_sp = c(pool = NA, asb1 = "#95D840FF", asb2 = "#95D840FF"), fill_vert = c(pool = NA, asb1 = "#95D840FF", asb2 = "#95D840FF"), color_ch = c(pool = NA, asb1 = "#95D840FF", asb2 = "#95D840FF"), fill_ch = c(pool = "white", asb1 = "#95D840FF", asb2 = "#95D840FF"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_San_Pedro_w$fric$PC1_PC2
plots_alpha_San_Pedro_d <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("San_Pedro_d"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#95D840FF", asb2 = "#95D840FF"), color_vert = c(pool = "grey50", asb1 = "#95D840FF", asb2 = "#95D840FF"), fill_sp = c(pool = NA, asb1 = "#95D840FF", asb2 = "#95D840FF"), fill_vert = c(pool = NA, asb1 = "#95D840FF", asb2 = "#95D840FF"), color_ch = c(pool = NA, asb1 = "#95D840FF", asb2 = "#95D840FF"), fill_ch = c(pool = "white", asb1 = "#95D840FF", asb2 = "#95D840FF"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_San_Pedro_d$fric$PC1_PC2
plots_alpha_La_Plata_w <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("La_Plata_w"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#FDE725FF", asb2 = "#FDE725FF"), color_vert = c(pool = "grey50", asb1 = "#FDE725FF", asb2 = "#FDE725FF"), fill_sp = c(pool = NA, asb1 = "#FDE725FF", asb2 = "#FDE725FF"), fill_vert = c(pool = NA, asb1 = "#FDE725FF", asb2 = "#FDE725FF"), color_ch = c(pool = NA, asb1 = "#FDE725FF", asb2 = "#FDE725FF"), fill_ch = c(pool = "white", asb1 = "#FDE725FF", asb2 = "#FDE725FF"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_La_Plata_w$fric$PC1_PC2
plots_alpha_La_Plata_d <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("La_Plata_d"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#FDE725FF", asb2 = "#FDE725FF"), color_vert = c(pool = "grey50", asb1 = "#FDE725FF", asb2 = "#FDE725FF"), fill_sp = c(pool = NA, asb1 = "#FDE725FF", asb2 = "#FDE725FF"), fill_vert = c(pool = NA, asb1 = "#FDE725FF", asb2 = "#FDE725FF"), color_ch = c(pool = NA, asb1 = "#FDE725FF", asb2 = "#FDE725FF"), fill_ch = c(pool = "white", asb1 = "#FDE725FF", asb2 = "#FDE725FF"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_La_Plata_d$fric$PC1_PC2
plots_alpha_Bocagrande_w <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Bocagrande_w"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#2166AC", asb2 = "#2166AC"), color_vert = c(pool = "grey50", asb1 = "#2166AC", asb2 = "#2166AC"), fill_sp = c(pool = NA, asb1 = "#2166AC", asb2 = "#2166AC"), fill_vert = c(pool = NA, asb1 = "#2166AC", asb2 = "#2166AC"), color_ch = c(pool = NA, asb1 = "#2166AC", asb2 = "#2166AC"), fill_ch = c(pool = "white", asb1 = "#2166AC", asb2 = "#2166AC"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_Bocagrande_w$fric$PC1_PC2
plots_alpha_Bocagrande_d <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Bocagrande_d"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#2166AC", asb2 = "#2166AC"), color_vert = c(pool = "grey50", asb1 = "#2166AC", asb2 = "#2166AC"), fill_sp = c(pool = NA, asb1 = "#2166AC", asb2 = "#2166AC"), fill_vert = c(pool = NA, asb1 = "#2166AC", asb2 = "#2166AC"), color_ch = c(pool = NA, asb1 = "#2166AC", asb2 = "#2166AC"), fill_ch = c(pool = "white", asb1 = "#2166AC", asb2 = "#2166AC"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_Bocagrande_d
plots_alpha_Rompido_w <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Rompido_w"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#D6604D", asb2 = "#D6604D"), color_vert = c(pool = "grey50", asb1 = "#D6604D", asb2 = "#D6604D"), fill_sp = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), fill_vert = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), color_ch = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), fill_ch = c(pool = "white", asb1 = "#D6604D", asb2 = "#D6604D"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_Rompido_w$fric$PC1_PC2
plots_alpha_Rompido_d <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Rompido_d"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey95", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#D6604D", asb2 = "#D6604D"), color_vert = c(pool = "grey50", asb1 = "#D6604D", asb2 = "#D6604D"), fill_sp = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), fill_vert = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), color_ch = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), fill_ch = c(pool = "white", asb1 = "#D6604D", asb2 = "#D6604D"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_Rompido_d$fric$PC1_PC2
plots_alpha_Rompido_d <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Rompido_d"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey75", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#D6604D", asb2 = "#D6604D"), color_vert = c(pool = "grey50", asb1 = "#D6604D", asb2 = "#D6604D"), fill_sp = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), fill_vert = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), color_ch = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), fill_ch = c(pool = "white", asb1 = "#D6604D", asb2 = "#D6604D"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_Rompido_d$fric$PC1_PC2
plots_alpha_Rompido_d <- mFD::alpha.multidim.plot(output_alpha_fd_multidim = alpha_fd_indices_invert, plot_asb_nm = c("Rompido_d"), ind_nm = c("fric"), faxes = NULL, faxes_nm = NULL, range_faxes = c(NA, NA), color_bg = "grey80", shape_sp = c(pool = 3, asb1 = 21, asb2 = 21), size_sp = c(pool = 0.7, asb1 = 3, asb2 = 3), color_sp = c(pool = "grey50", asb1 = "#D6604D", asb2 = "#D6604D"), color_vert = c(pool = "grey50", asb1 = "#D6604D", asb2 = "#D6604D"), fill_sp = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), fill_vert = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), color_ch = c(pool = NA, asb1 = "#D6604D", asb2 = "#D6604D"), fill_ch = c(pool = "white", asb1 = "#D6604D", asb2 = "#D6604D"), alpha_ch = c(pool = 1, asb1 = 0.3, asb2 = 0.3), shape_centroid_fdis = c(asb1 = 22, asb2 = 24), shape_centroid_fdiv = c(asb1 = 22, asb2 = 24), shape_centroid_fspe = 23,color_centroid_fspe = "black", size_sp_nm = 3, color_sp_nm = "black", plot_sp_nm = NULL, fontface_sp_nm = "plain", save_file = FALSE, check_input = TRUE)
plots_alpha_Rompido_d$fric$PC1_PC2
savehistory("C:/Users/vical/Desktop/Analisis_diversidad_funcional/plots_fric.R")
